from __future__ import annotations

from typing import Any, Dict, Optional, Protocol, runtime_checkable


@runtime_checkable
class Transport(Protocol):
    def connect(self) -> bool: ...
    def disconnect(self) -> None: ...
    def receive_full_response(self, *, buffer_size: int = 8192, timeout: float = 15.0) -> Any: ...
    def send_command(self, command_type: str, params: Optional[Dict[str, Any]] = None) -> Any: ...
